version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      security-updates:
        applies-to: security-updates
        patterns: ['*']
      aws-sdk:
        patterns:
          - '@aws-sdk/*'
